spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    name: tacocloud
    generate-unique-name: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
